# jekyll-seo-tag
title: "How the ICC Works"
description: "The ICC is a court of last resort. It has to adhere to a great number of rules to determine where and when it can operate."
url: "http://how-the-icc-works.aba-icc.org" # the base hostname & protocol for your site
author: []
twitter:
  username: budparr
facebook:
  app_id:
  publisher:
  admins:
logo: /assets/images/jekyll-white.svg
google_site_verification:
github:
  username: budparr
owner: The New Dynamic
# manifest
short_name: The Shortname
display: fullscreen

# development meta data
image_url: http://thenewdynamic.imgix.net
google_analytics_id: UA-xxxxx-4
version: 3.0.3
incremental: true
#port: 3575


# Settings
production: false
full_rebuild: true
compress_html:
  ignore:
    envs: [development]
  profile: false
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
destination: public
source: src
plugins_dir:  /_app/_plugins
layouts_dir:  /_app/_layouts
includes_dir: /_app/_includes


# CONTENT
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - node_modules
  - package.json

processes:
  - ''
  - jurisdictional-triggers
  - referrals-and-communication
  - preliminary-examination
  - investigation
  - arrest-warrant-and-summons
  - confirmation-of-charges
  - trial-and-appeal
  - sentencing-and-reparations


collections:
  referrals-and-communication:
    output: true
    permalink: '/:path/'
  preliminary-examination:
    output: true
    permalink: '/:path/'
  investigation:
    output: true
    permalink: '/:path/'
  arrest-warrant-and-summons:
    output: true
    permalink: '/:path/'
    color:
  confirmation-of-charges:
    output: true
    permalink: '/:path/'
  trial-and-appeal:
    output: true
    permalink: '/:path/'
  sentencing-and-reparations:
    output: true
    permalink: '/:path/'
  atrocity-crimes:
    output: true
    permalink: '/:path/'


defaults:
  - scope:
      path: ''
    values:
      layout: page-single
